version: 2
updates:
  - package-ecosystem: cargo
    directory: /core
    schedule: {interval: weekly}
    groups:
      rust-minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: pub
    directory: /apps/mobile
    schedule: {interval: weekly}
  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: weekly}

