name: Semgrep CE

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "29 5 * * 3"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  semgrep:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v6
      - run: semgrep scan --config auto --error
